kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "common.names.fullname" . }}-node
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    component: node
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      component: node
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: node
    spec:
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "instance.hetzner.cloud/is-root-server"
                  operator: NotIn
                  values:
                    - "true"
      serviceAccount: {{ include "common.names.fullname" . }}
      containers:
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
          args:
            - --kubelet-registration-path={{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/socket
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /run/csi
            - name: registration-dir
              mountPath: /registration
        - name: hcloud-csi-driver
          image: {{ .Values.node.image }}
          imagePullPolicy: {{ .Values.node.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///run/csi/socket
            - name: METRICS_ENDPOINT
              value: 0.0.0.0:9189
            - name: ENABLE_METRICS
              value: "{{ .Values.metrics.enabled }}"
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ if .Values.secret.existingSecretName }}{{ .Values.secret.existingSecretName }}{{ else }}{{ include "common.names.fullname" . }}{{ end }}"
                  key: hcloudApiToken
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /run/csi
            - name: device-dir
              mountPath: /dev
          securityContext:
            privileged: true
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: 9189
              name: metrics
            {{- end }}
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
        - name: liveness-probe
          imagePullPolicy: Always
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          volumeMounts:
            - mountPath: /run/csi
              name: plugin-dir
      volumes:
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
