{{- if not .Values.secret.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- if .Values.secret.hcloudApiToken }}
  hcloudApiToken: {{ .Values.secret.hcloudApiToken | default "" | b64enc }}
  {{- else }}
  {{ printf "You must either provide secret.hcloudApiToken or secret.existingSecretName" | fail }}
  {{- end }}
{{- end -}}
