apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Delete" }}
