apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hetzner.cloud
allowVolumeExpansion: true
parameters:
  csiNodeSelector: ""
  type: "ssd"        # or "default"
  fsType: "ext4"
reclaimPolicy: Delete
volumeBindingMode: Immediate

